[phases.setup]
aptPkgs = [
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxrender1",
  "libxss1",
  "libxtst6",
  "ca-certificates",
  "fonts-liberation",
  "libappindicator1",
  "libnss3",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "xdg-utils",
  "wget"
]